### ISSUE TITLE
Relation redeclaration using different name

### ISSUE THREAD

**Issue by romshark** [romshark/TypeBook#1]
It is possible to create multiple relations of the same type just with different names:
```yaml
entity types:
  Movie:
    relations:
      actors:
        type: ActedIn
        direction: inbound
        related type: Actor
      actors2:
        type: ActedIn
        direction: inbound
        related type: Actor
```
 which is obviously a bug that can be solved by performing an additional relation duplication verification step.
